
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChatService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Design_Time_Addresses/Practicum56Library/ChatService/?wsdl")
public class ChatService
    extends Service
{

    private final static URL CHATSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHATSERVICE_EXCEPTION;
    private final static QName CHATSERVICE_QNAME = new QName("http://tempuri.org/", "ChatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Design_Time_Addresses/Practicum56Library/ChatService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHATSERVICE_WSDL_LOCATION = url;
        CHATSERVICE_EXCEPTION = e;
    }

    public ChatService() {
        super(__getWsdlLocation(), CHATSERVICE_QNAME);
    }

    public ChatService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHATSERVICE_QNAME, features);
    }

    public ChatService(URL wsdlLocation) {
        super(wsdlLocation, CHATSERVICE_QNAME);
    }

    public ChatService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHATSERVICE_QNAME, features);
    }

    public ChatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChatService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IChatService
     */
    @WebEndpoint(name = "BasicHttpBinding_IChatService")
    public IChatService getBasicHttpBindingIChatService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IChatService"), IChatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IChatService
     */
    @WebEndpoint(name = "BasicHttpBinding_IChatService")
    public IChatService getBasicHttpBindingIChatService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IChatService"), IChatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHATSERVICE_EXCEPTION!= null) {
            throw CHATSERVICE_EXCEPTION;
        }
        return CHATSERVICE_WSDL_LOCATION;
    }

}
